version: '3.8'

services:
  freegamesapi:
    image: freegamesapi
    build:
      context: .
    ports:
      - "8081:8080"
    networks:
      - freegamesapi-network
    depends_on:
      - "redisfreegamesapi"

  redisfreegamesapi:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - freegamesapi-network

networks: 
    freegamesapi-network:
        driver: bridge